### ISSUE TITLE
Resolve the version of Maven plugins properly

### ISSUE THREAD

**Issue by fpavageau** [ekino/ekino-tools-version#13]
The versions of plugins are fetched via the Gradle-specific POM, with
```scala
private def getPluginCoordinates(pluginId: String): String = s"$pluginId:$pluginId.gradle.plugin"
```
which doesn't work for Maven plugins, and their latest release is not resolved.

When the id of the plugin is already composed of `groupId:artifactId` (i.e. a Maven plugin), we should directly use it instead.

**Comment by philippeagra** [comment]
fixed by https://github.com/ekino/ekino-tools-version/pull/15
