### ISSUE TITLE
Upgrade to Play 2.7.x

### ISSUE THREAD

**Issue by clemstoquart** [ekino/ekino-tools-version#22]
Play 2.7.2 has been released few days ago. I think it's time for us to upgrade to the last Play release.

Migration doesn't seem too hard : https://www.playframework.com/documentation/2.7.x/Migration27

**Comment by philippeagra** [comment]
Hello, unfortunately gradle still does not support PLAY_2_7_X but if you launch the application with the command **sbt run** it will use the last playframework version (2.7.1) with only a warning on contentSecurityPolicy deprecation.

**Comment by clemstoquart** [comment]
Indeed. Gradle Play 2.7 support is tracked here : https://github.com/gradle/gradle/issues/6362

**Comment by clemstoquart** [comment]
The issue for Play 2.7 in the new Play plugin https://github.com/gradle/playframework/issues/92

**Comment by celcius112** [comment]
Done in https://github.com/ekino/ekino-tools-version/commit/4123698c20fa2cc51fbb66e487f6e7784bac3443
