### ISSUE TITLE
Migrating from Gradle’s standard Play plugin

### ISSUE THREAD

**Issue by clemstoquart** [ekino/ekino-tools-version#23]
Hi,
I think we should migrate to https://gradle.github.io/playframework/ since the standard Play plugin is going to be deprecated in Gradle 5.5 and removed in Gradle 6.

**Comment by philippeagra** [comment]
Hello,
I have added the PR, the integration is better than with the embedded plugin (better intelliJ support). Sadly the debug is not supported out of the box (we can use sbt for that)
