### ISSUE TITLE
Handle NPM semantic versioning

### ISSUE THREAD

**Issue by celcius112** [ekino/ekino-tools-version#3]
As the title suggests, it would be nice to handle NPM packages. 

A probable difficulty would come from the handling of NPM's [semantic versioning](https://docs.npmjs.com/misc/semver) (but it's a nice problem to resolve 😄).

Ideas and solutions are welcome.

**Comment by philippeagra** [comment]
Hello, i have started a PR : https://github.com/ekino/ekino-tools-version/pull/6
It's not finished.

**Comment by celcius112** [comment]
Hello @philippeagra, thanks for the nice PR 😀 !

I'll let this issue open, since semantic versioning is not yet completely taken care of, but I'll rename it accordingly.

**Comment by celcius112** [comment]
Hello @clemstoquart,
I think there might still be some work to do, since at the moment the application does not handle npm ranges. The most important part is done though.

**Comment by celcius112** [comment]
For future reference, the commit https://github.com/ekino/ekino-tools-version/pull/32 changes the parsing logic so that a dependency retrieved from the package.json is cross-referenced with the lock file (package-lock or yarn.lock), so that the semantic versioning logic is handled by yarn or npm
