### ISSUE TITLE
Handle Gradle's new plugin version management using a gradle.properties

### ISSUE THREAD

**Issue by celcius112** [ekino/ekino-tools-version#46]
Since Gradle 5.6, plugin versions can be defined globally in a `plugins {}` block inside a `pluginManagement {}` block, as defined [here](https://docs.gradle.org/5.6/userguide/plugins.html#sec:plugin_version_management) (with an example). As says in the link it `allows plugin versions to be take [sic] from gradle.properties`. 

A proposed implementation would be to lazily parse the `settings.gradle` (in order to retrieve the version keys) if a plugin's version is not present in the `build.gradle`'s `plugins {}` block.

**Comment by clemstoquart** [comment]
Hi,
Is this issue still relevant ?
